### PR TITLE
Fixed compatibility with TS 4.8.4

### PR DESCRIPTION
**Pull request by lurbancz**

### CODE REVIEW

**Comment by krewi1** [comment]
Hi, first of all thanks for your pull request. On first look the typing doesn't seem to be correct, because on line #15 there are cases for handling different types then object. Can you please provide in description or rather in some spec file case what should work 🙏 ?

**Comment by lurbancz** [comment]
We have issue with TS 4.8.4 compatibility.

After upgrade on TS 4.8.4 we have issue with typings on Object.assign function (line 32 on old or 36 on PR) on currentValue parameter.
As you can see in the screen there is "No possible overload matches this call".
image
When T is used as {} (line 25 on old or 29 on PR) then we extend T with {} on renderHookInsideParent function.

Then is same issue on renderHook function where we also extend T with {}.

I hope it's clear.

Thanks,
Lukáš

**Comment by krewi1** [comment]
Thanks for the clarification, but i don't thing this is correct fix. T still should be of type any because it can be literally whatever. I think there really is a problem in typings. Thing is that on line #29 i was casting to type T, which is obviously wrong. It should be casted to actual returned type: `T extends BoxedTypes ? Box<T> : T`, but on line 38 i am evaluating this condition `typeof result === "object" ? result : { value: result }`, so that conditional generic is also wrong and should be kind of reversed to `T extends {} ? T : Box<T>`. Overall i think the best solution is to introduce helper type (lets call it CurrentValue for now, if you can think of better naming do it) `type CurrentValue<T> = T extends {} ? T : Box<T>` and use this for return type and also for casting.

**Comment by krewi1** [comment]
Hopefully the explanation was clear, if not do not hesitate to contact me on email or https://discord.gg/CTFSd3Rq here for example. We can discuss it further.

**Review by krewi1 — APPROVED** [review]

**Pull request merged**
